### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by SXRguyinMA** [Decuwu/femboylua#7]
I'm getting errors loading the lua after the latest 2T1 update. Tried uninstalling/reinstalling through the menu. Also downloaded from here but I'm not sure where to put the files. See attached screenshot for errors.
![femboyerror](https://github.com/user-attachments/assets/85f78081-fe67-4047-a125-cd8d82ba0651)

**Comment by Decuwu** [comment]
Will fix soon

use this [downloader](https://github.com/Decuwu/FemboyV3/blob/main/FemboyV3Downloader/FemboyV3Downloader.exe) to automatically download all needed files

**Comment by Decuwu** [comment]
Latest update has fixed this, please download it from https://github.com/Decuwu/FemboyV3/releases/tag/v3.9.4. 

If you are unsure on how to install then use the [downloader](https://github.com/Decuwu/FemboyV3/blob/main/FemboyV3Downloader/FemboyV3Downloader.exe) i linked above
